[package]
name = "day8"
version = "0.1.0"
authors = ["Martin Gabel <martin.gabel@icechair.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
png = "0.11.0"
itertools = "0.8.2"